<?php
include ('PDO/conexao.php');

$cod = 1;

$sth = $pdo->prepare('SELECT TB_INSTITUICAO.TB_INSTITUICAO_NOME AS Nome,
TB_INSTITUICAO.TB_INSTITUICAO_ENDERECO AS Endereco,
TB_INSTITUICAO.TB_INSTITUICAO_COD AS Codigo,
TB_INSTITUICAO.TB_INSTITUICAO_END_NUM AS Numero_endereco,
TB_INSTITUICAO.TB_INSTITUICAO_CIDADE AS Bairro,
TB_INSTITUICAO.TB_INSTITUICAO_CEP AS Cep,
TB_INSTITUICAO.TB_INSTITUICAO_TELEFONE AS Telefone,
TB_INSTITUICAO.TB_INSTITUICAO_EMAIL AS Email,
TB_INSTITUICAO.TB_INSTITUICAO_SENHA AS Senha,
TB_INSTITUICAO.TB_INSTITUICAO_IMG_USER AS Foto 
FROM `TB_INSTITUICAO`
WHERE TB_INSTITUICAO.TB_INSTITUICAO_ID LIKE 1');

$sth->execute();

$resultados = $sth->fetchAll(PDO::FETCH_ASSOC);
?>